### ISSUE TITLE
Toggle for UI modification on Actors tab.

### ISSUE THREAD

**Issue by JLtheking2** [crash1115/ready-check#1]
Hello there! Really cool mod so far, tried it out in a session today and my players enjoyed it.

Unfortunately, there is a minor conflict with the popular [Permission Viewer](https://github.com/kakaroto/fvtt-module-permission-viewer) mod, where the rendering of the tick or cross causes the renderer to display it in the same position as the display from the Permission Viewer.

Is it possible to have this feature be a toggle? I think the only main thing I would like to keep is just the tick or cross display on the bottom left players panel.

Thanks again for publishing this mod!

**Comment by crash1115** [comment]
Hey, glad you're enjoying the module!

The ready icon displaying in the Actor's tab is entirely unintentional - a fun side effect of the way Permission viewer makes changes to the content there. I'll have a patch out to remove that sometime today.

Thanks for the report!
